package com.muxistudio.chaser.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.muxistudio.chaser.db.Wordbank;
import com.muxistudio.chaser.db.Word;

import com.muxistudio.chaser.db.WordbankDao;
import com.muxistudio.chaser.db.WordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wordbankDaoConfig;
    private final DaoConfig wordDaoConfig;

    private final WordbankDao wordbankDao;
    private final WordDao wordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wordbankDaoConfig = daoConfigMap.get(WordbankDao.class).clone();
        wordbankDaoConfig.initIdentityScope(type);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        wordbankDao = new WordbankDao(wordbankDaoConfig, this);
        wordDao = new WordDao(wordDaoConfig, this);

        registerDao(Wordbank.class, wordbankDao);
        registerDao(Word.class, wordDao);
    }
    
    public void clear() {
        wordbankDaoConfig.clearIdentityScope();
        wordDaoConfig.clearIdentityScope();
    }

    public WordbankDao getWordbankDao() {
        return wordbankDao;
    }

    public WordDao getWordDao() {
        return wordDao;
    }

}
