package com.muxistudio.chaser.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "WORD".
 */
@Entity
public class Word {

    @Id
    private Long id;
    private String word;
    private String phonetic;
    private String explain;
    private Integer classId;

    @Generated
    public Word() {
    }

    public Word(Long id) {
        this.id = id;
    }

    @Generated
    public Word(Long id, String word, String phonetic, String explain, Integer classId) {
        this.id = id;
        this.word = word;
        this.phonetic = phonetic;
        this.explain = explain;
        this.classId = classId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public String getPhonetic() {
        return phonetic;
    }

    public void setPhonetic(String phonetic) {
        this.phonetic = phonetic;
    }

    public String getExplain() {
        return explain;
    }

    public void setExplain(String explain) {
        this.explain = explain;
    }

    public Integer getClassId() {
        return classId;
    }

    public void setClassId(Integer classId) {
        this.classId = classId;
    }

}
