package com.muxistudio.chaser.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "WORDBANK".
 */
@Entity
public class Wordbank {

    @Id
    private Long id;
    private String category;
    private String name;
    private Integer classId;

    @Generated
    public Wordbank() {
    }

    public Wordbank(Long id) {
        this.id = id;
    }

    @Generated
    public Wordbank(Long id, String category, String name, Integer classId) {
        this.id = id;
        this.category = category;
        this.name = name;
        this.classId = classId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getClassId() {
        return classId;
    }

    public void setClassId(Integer classId) {
        this.classId = classId;
    }

}
